//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mycook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingredients_to_buy
    {
        public decimal id_shoppinglist { get; set; }
        public decimal id_ingredient { get; set; }
        public Nullable<decimal> amount { get; set; }
    
        public virtual ingredient ingredient { get; set; }
        public virtual shopping_list shopping_list { get; set; }
    }
}
