//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mycook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public recipe()
        {
            this.images_recipe = new HashSet<images_recipe>();
            this.ingredients_recipe = new HashSet<ingredients_recipe>();
            this.steps = new HashSet<step>();
            this.users = new HashSet<user>();
            this.preferences = new HashSet<preference>();
            this.meal_plan = new HashSet<meal_plan>();
        }
    
        public decimal id_recipe { get; set; }
        public string name_recipe { get; set; }
        public Nullable<decimal> calories_portion { get; set; }
        public Nullable<decimal> portions { get; set; }
        public Nullable<decimal> fat_per_portion { get; set; }
        public Nullable<decimal> saturatedfat_per_portion { get; set; }
        public Nullable<decimal> protein_per_portion { get; set; }
        public Nullable<decimal> sodium_per_portion { get; set; }
        public Nullable<decimal> cholesterol_per_portion { get; set; }
        public Nullable<decimal> carbs_per_portion { get; set; }
        public Nullable<decimal> sugar_per_portion { get; set; }
        public Nullable<decimal> fibre_per_portion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<images_recipe> images_recipe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ingredients_recipe> ingredients_recipe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<step> steps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<preference> preferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meal_plan> meal_plan { get; set; }
        public string ErrorMessage { get; internal set; }
    }
}
