//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mycook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class images_recipe
    {
        public decimal id_image { get; set; }
        public string url { get; set; }
        public decimal id_recipe { get; set; }
    
        public virtual recipe recipe { get; set; }
    }
}
