//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mycook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class preference_plan
    {
        public decimal id_preference { get; set; }
        public string description { get; set; }
        public Nullable<decimal> value { get; set; }
        public Nullable<decimal> id_user { get; set; }
    
        public virtual user user { get; set; }
    }
}
