//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mycook.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mycookEntities : DbContext
    {
        public mycookEntities()
            : base("name=mycookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<images_recipe> images_recipe { get; set; }
        public virtual DbSet<ingredient> ingredients { get; set; }
        public virtual DbSet<ingredients_recipe> ingredients_recipe { get; set; }
        public virtual DbSet<ingredients_to_buy> ingredients_to_buy { get; set; }
        public virtual DbSet<meal_plan> meal_plan { get; set; }
        public virtual DbSet<preference_plan> preference_plan { get; set; }
        public virtual DbSet<preference> preferences { get; set; }
        public virtual DbSet<recipe> recipes { get; set; }
        public virtual DbSet<shopping_list> shopping_list { get; set; }
        public virtual DbSet<step> steps { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
