//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mycook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shopping_list
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shopping_list()
        {
            this.ingredients_to_buy = new HashSet<ingredients_to_buy>();
        }
    
        public Nullable<decimal> id_mealplan { get; set; }
        public Nullable<decimal> id_user { get; set; }
        public decimal id_shoppinglist { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ingredients_to_buy> ingredients_to_buy { get; set; }
        public virtual meal_plan meal_plan { get; set; }
        public virtual user user { get; set; }
    }
}
