//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mycook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class ingredient
    {
        mycookEntities me = new mycookEntities();

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ingredient()
        {
            this.ingredients_recipe = new HashSet<ingredients_recipe>();
            this.ingredients_to_buy = new HashSet<ingredients_to_buy>();
        }
    
        public decimal id_ingredient { get; set; }
        public string name_ingredient { get; set; }
        public string status { get; set; }

        public IEnumerable<SelectListItem> ingredientesbd { get; set; }

        public List<ingredient> ListaIngredients()
        {
            List<ingredient> aux = new List<ingredient>();

            foreach(ingredient i in me.ingredients)
            {
                aux.Add(i);
            }

            return aux;

        }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ingredients_recipe> ingredients_recipe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ingredients_to_buy> ingredients_to_buy { get; set; }
        public string ErrorMessage { get; internal set; }
    }
}
