//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mycook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingredients_recipe
    {
        public decimal id_recipe { get; set; }
        public String name_aux { get; set; }
        public decimal id_ingredient { get; set; }
        public Nullable<decimal> quantity_per_portion { get; set; }
    
        public virtual ingredient ingredient { get; set; }
        public virtual recipe recipe { get; set; }
    }
}
